[theme]
inherit = "sphinx_wagtail_theme"
stylesheets = [
    "dist/theme.css",
    "uom_custom.css",
]
sidebars = [
    "searchbox.html",
    "globaltoc.html",
    "uom_logo_sidebar.html",
]
pygments_style = { default = "none" }

[options]
project_name = "uom_sphinx_wagtail_theme"
searchbox_text = "Search notes"
logo = "img/uom_logo_white.png"
logo_alt = "University of Manchester"
logo_height = ""
logo_url = ""
logo_width = "88"
header_links = ""
footer_links = ""
github_url = ""
